OOP Exercise
crisgahur/OOPExercise pull request #1
Opened 2023-01-21 18:44 UTC by crisgahur

Uploading exercise of ticket [BACK-4](https://vulky.atlassian.net/browse/BACK-4).

2023-01-23 16:57 UTC, MauroCaro commented
Title is not correct "POO Exercise 1".

Also please add a good description for this PR

2023-01-23 16:57 UTC, MauroCaro commented on README.md
> +# POOExerciseONE
Awesome! 🚀

2023-01-23 16:58 UTC, MauroCaro commented on src/main/java/com/mycompany/exerciseone/Pedro.java
> +
Please delete empty space

2023-01-23 16:59 UTC, MauroCaro commented on src/main/java/com/mycompany/exerciseone/Person.java
> +
Please delete empty space

2023-01-23 17:01 UTC, MauroCaro commented on src/main/java/com/mycompany/exerciseone/PersonModel.java
> +
Please delete empty space

2023-01-23 17:01 UTC, MauroCaro commented on src/main/java/com/mycompany/exerciseone/PersonModel.java
> +       public PersonModel(){};
Indent code

2023-01-23 17:01 UTC, MauroCaro commented on src/main/java/com/mycompany/exerciseone/PersonModel.java
> +
Please delete empty space

2023-01-23 17:02 UTC, MauroCaro commented on src/main/java/com/mycompany/exerciseone/Person.java
> +           System.out.println("Hellooo");
Indent code

2023-01-23 17:04 UTC, MauroCaro commented on src/main/java/com/mycompany/exerciseone/Pepita.java
> +;
What is this?

2023-01-23 17:05 UTC, MauroCaro commented on src/main/java/com/mycompany/exerciseone/ExerciseOne.java
> +
Delete empty space

2023-01-23 17:05 UTC, MauroCaro requested changes
Check comments

2023-01-24 01:44 UTC, crisgahur commented on src/main/java/com/mycompany/exerciseone/Pedro.java
> +
Ok, done.

2023-01-24 01:44 UTC, crisgahur commented on src/main/java/com/mycompany/exerciseone/Person.java
> +
Ok, done.

2023-01-24 01:44 UTC, crisgahur commented on src/main/java/com/mycompany/exerciseone/PersonModel.java
> +
Ok, done.

2023-01-24 01:44 UTC, crisgahur commented on src/main/java/com/mycompany/exerciseone/PersonModel.java
> +       public PersonModel(){};
Ok, done.

2023-01-24 01:44 UTC, crisgahur commented on src/main/java/com/mycompany/exerciseone/PersonModel.java
> +
Ok, done.

2023-01-24 01:45 UTC, crisgahur commented on src/main/java/com/mycompany/exerciseone/Person.java
> +           System.out.println("Hellooo");
Ok, done.

2023-01-24 01:48 UTC, crisgahur commented on src/main/java/com/mycompany/exerciseone/ExerciseOne.java
> +
Ok, done

2023-01-24 01:49 UTC, crisgahur commented on README.md
> +# POOExerciseONE
Thankss

2023-01-27 17:29 UTC, MauroCaro approved these changes

2023-01-27 17:29 UTC, MauroCaro commented
PR approved and can be merged!

2023-01-27 18:13 UTC, merged